"""sextant's C++ core; use the sextant package, not this module"""

from collections.abc import Callable, Sequence
import os
from typing import Any, IO, overload

import numpy
import numpy.typing

import sextant._enums

import collections.abc
from typing import Literal, TypedDict

from numpy.typing import ArrayLike
from typing_extensions import TypeAlias, Unpack


# Generated by tools/gen_stubs.py from the binding's name and field tables.

LineStyleLike: TypeAlias = sextant._enums.LineStyle | Literal["solid", "dashed", "dotted", "dashdot", "none", "-", "--", ":", "-.", ""]
MarkerStyleLike: TypeAlias = sextant._enums.MarkerStyle | Literal["none", "circle", "square", "triangle", "cross", "plus", "diamond", "o", "s", "^", "x", "+", "D", "d", ""]
ColormapLike: TypeAlias = sextant._enums.Colormap | Literal["viridis", "plasma", "inferno", "magma", "cividis", "turbo", "coolwarm", "gray", "grey"]
CapStyleLike: TypeAlias = sextant._enums.CapStyle | Literal["flat", "arrow"]
AxisPositionLike: TypeAlias = sextant._enums.AxisPosition | Literal["auto", "low", "mid", "high"]
LegendAnchorLike: TypeAlias = sextant._enums.LegendAnchor | Literal["inside_tl", "inside_tr", "inside_bl", "inside_br", "outside_tl", "outside_tr", "outside_bl", "outside_br", "outside_lt", "outside_lb", "outside_rt", "outside_rb"]
ColorbarAnchorLike: TypeAlias = sextant._enums.ColorbarAnchor | Literal["left", "right", "top", "bottom"]
HAlignLike: TypeAlias = sextant._enums.HAlign | Literal["left", "center", "right", "centre"]
PanelThemeLike: TypeAlias = sextant._enums.PanelTheme | Literal["dark", "light", "classic"]
ProjectionLike: TypeAlias = sextant._enums.Projection | Literal["orthographic", "perspective", "ortho", "persp"]
PlaneOrientationLike: TypeAlias = sextant._enums.PlaneOrientation | Literal["xy", "yz", "zx"]
EventKindLike: TypeAlias = sextant._enums.EventKind | Literal["close", "mouse_down", "mouse_up", "mouse_move", "scroll", "key_down", "key_up", "resize", "pick", "close_event", "button_press_event", "button_release_event", "motion_notify_event", "scroll_event", "key_press_event", "key_release_event", "resize_event", "pick_event"]
PickKindLike: TypeAlias = sextant._enums.PickKind | Literal["none", "line", "scatter", "scatter_z", "bar", "heatmap", "bar3d", "surface", "surface_tri", "scatter3d", "line3d"]
EventConsumedLike: TypeAlias = sextant._enums.EventConsumed | Literal["none", "select", "navigate", "grid_drag"]


class ErrorBarOptions(TypedDict, total=False):
    color: str | tuple[float, ...] | None
    linewidth: float
    capsize: float
    capstyle: CapStyleLike
    boxwidth: float
    box_alpha: float

class FigureMargins(TypedDict, total=False):
    left: float
    right: float
    top: float
    bottom: float

class LineOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    linewidth: float
    linestyle: LineStyleLike
    name: str
    show_legend: bool
    alpha: float
    loop: bool
    errorbar: ErrorBarOptions
    hint_labels: collections.abc.Sequence[str]

class ScatterOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    size: float
    marker: MarkerStyleLike
    name: str
    show_legend: bool
    alpha: float
    edgecolor: str | tuple[float, ...] | None
    edge_alpha: float
    edge_linewidth: float
    errorbar: ErrorBarOptions
    hint_labels: collections.abc.Sequence[str]

class ScatterZOptions(TypedDict, total=False):
    cmap: ColormapLike
    size: float
    marker: MarkerStyleLike
    alpha: float
    edgecolor: str | tuple[float, ...] | None
    edge_alpha: float
    edge_linewidth: float
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    show_legend: bool
    errorbar: ErrorBarOptions
    hint_labels: collections.abc.Sequence[str]

class BarOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    width: float
    alpha: float
    name: str
    show_legend: bool
    edgecolor: str | tuple[float, ...]
    linewidth: float
    errorbar: ErrorBarOptions
    hint_labels: collections.abc.Sequence[str]

class HeatmapOptions(TypedDict, total=False):
    cmap: ColormapLike
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    origin: str
    contours: collections.abc.Sequence[float]
    contour_color: str | tuple[float, ...]
    contour_linewidth: float
    contour_labels: bool
    contour_fontsize: float
    hint_labels: collections.abc.Sequence[str]

class GridOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    linestyle: LineStyleLike
    linewidth: float

class AxesStyle(TypedDict, total=False):
    background: str | tuple[float, ...]
    spine_color: str | tuple[float, ...]
    spine_linewidth: float
    spine_bottom: bool
    spine_left: bool
    spine_top: bool
    spine_right: bool
    xaxis_y: AxisPositionLike
    xaxis_z: AxisPositionLike
    yaxis_x: AxisPositionLike
    yaxis_z: AxisPositionLike
    zaxis_x: AxisPositionLike
    zaxis_y: AxisPositionLike
    origin_x: float | None
    origin_y: float | None
    origin_z: float | None
    frame_margin: float
    show_xticks: bool
    show_yticks: bool
    show_zticks: bool
    tick_color: str | tuple[float, ...]
    tick_length: float
    tick_linewidth: float
    label_color: str | tuple[float, ...]
    label_fontsize: float
    title_color: str | tuple[float, ...]
    title_fontsize: float
    xtitle_color: str | tuple[float, ...]
    xtitle_fontsize: float
    ytitle_color: str | tuple[float, ...]
    ytitle_fontsize: float
    ztitle_color: str | tuple[float, ...]
    ztitle_fontsize: float
    font_path: str

class LegendOptions(TypedDict, total=False):
    anchor: LegendAnchorLike
    margin: float
    offset_x: float
    offset_y: float
    fontsize: float
    frameon: bool
    text_color: str | tuple[float, ...]
    frame_color: str | tuple[float, ...]
    border_color: str | tuple[float, ...]
    border_linewidth: float
    font_path: str

class ColorbarOptions(TypedDict, total=False):
    anchor: ColorbarAnchorLike
    width: float
    margin: float
    offset_x: float
    offset_y: float
    fontsize: float
    text_color: str | tuple[float, ...]
    border_color: str | tuple[float, ...]
    border_linewidth: float
    font_path: str

class SuptitleOptions(TypedDict, total=False):
    fontsize: float
    color: str | tuple[float, ...]
    font_path: str
    align: HAlignLike
    offset_x: float
    offset_y: float

class PngExportOptions(TypedDict, total=False):
    peel_layers: int
    dpi: float

class SvgExportOptions(TypedDict, total=False):
    max_splits: int
    max_tests: int

class FigureOptions(TypedDict, total=False):
    width: int
    height: int
    title: str
    resizable: bool
    dpi: float
    subplot_col_gap: float
    subplot_row_gap: float
    margins: FigureMargins
    background: str | tuple[float, ...]
    panel_width: float
    supersample: int
    vsync: bool
    theme: PanelThemeLike

class ErrorBar3DOptions(TypedDict, total=False):
    color: str | tuple[float, ...] | None
    linewidth: float
    capsize: float
    capstyle: CapStyleLike
    boxwidth: float
    box_alpha: float
    edge_alpha: float

class Plane2DOptions(TypedDict, total=False):
    alpha: float
    visible: bool

class Bar3DOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    alpha: float
    width: float
    depth: float
    bottom: float
    shading: float
    edges: bool
    edgecolor: str | tuple[float, ...]
    edge_alpha: float
    edge_linewidth: float
    name: str
    show_legend: bool
    hint_labels: collections.abc.Sequence[str]

class SurfaceOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    colormap: bool
    cmap: ColormapLike
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    show_legend: bool
    alpha: float
    shading: float
    edges: bool
    edgecolor: str | tuple[float, ...]
    edge_alpha: float
    edge_linewidth: float
    hint_labels: collections.abc.Sequence[str]

class SurfaceTriOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    cmap: ColormapLike
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    show_legend: bool
    alpha: float
    shading: float
    edges: bool
    edgecolor: str | tuple[float, ...]
    edge_alpha: float
    edge_linewidth: float
    hint_labels: collections.abc.Sequence[str]

class Scatter3DOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    size: float
    marker: MarkerStyleLike
    alpha: float
    edgecolor: str | tuple[float, ...] | None
    edge_alpha: float
    edge_linewidth: float
    depthshade: float
    cmap: ColormapLike
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    show_legend: bool
    errorbar: ErrorBar3DOptions
    hint_labels: collections.abc.Sequence[str]

class Line3DOptions(TypedDict, total=False):
    color: str | tuple[float, ...]
    linewidth: float
    alpha: float
    loop: bool
    depthshade: float
    cmap: ColormapLike
    vmin: float
    vmax: float
    colorbar: bool
    name: str
    show_legend: bool
    errorbar: ErrorBar3DOptions
    hint_labels: collections.abc.Sequence[str]

class Box3DStyle(TypedDict, total=False):
    panes: bool
    pane_color: str | tuple[float, ...]
    pane_edge_color: str | tuple[float, ...]
    margin: float

class Camera3D(TypedDict, total=False):
    azimuth: float
    elevation: float
    target: tuple[float, float, float]
    zoom: float
    projection: ProjectionLike
    fov: float

class ExportOptions(PngExportOptions, SvgExportOptions, total=False): ...


class ErrorBar:
    """
    Per-point error-bar data for line/scatter/scatter_z/bar (err=...).
    Offsets from the point, magnitude-valued; one end given means symmetric.
    cap_* draw the capped whisker, box_* a box; zero draws nothing on that side.
    Each given array holds one entry per point.
    """

    def __init__(self, *, x_cap_lo: ArrayLike | None = None, x_cap_hi: ArrayLike | None = None, x_box_lo: ArrayLike | None = None, x_box_hi: ArrayLike | None = None, y_cap_lo: ArrayLike | None = None, y_cap_hi: ArrayLike | None = None, y_box_lo: ArrayLike | None = None, y_box_hi: ArrayLike | None = None) -> None: ...

class ErrorBar3D:
    """ErrorBar for scatter3d/line3d, with a z axis. Same rules as ErrorBar."""

    def __init__(self, *, x_cap_lo: ArrayLike | None = None, x_cap_hi: ArrayLike | None = None, x_box_lo: ArrayLike | None = None, x_box_hi: ArrayLike | None = None, y_cap_lo: ArrayLike | None = None, y_cap_hi: ArrayLike | None = None, y_box_lo: ArrayLike | None = None, y_box_hi: ArrayLike | None = None, z_cap_lo: ArrayLike | None = None, z_cap_hi: ArrayLike | None = None, z_box_lo: ArrayLike | None = None, z_box_hi: ArrayLike | None = None) -> None: ...

class LineData:
    def __init__(self, x: ArrayLike, y: ArrayLike) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    def __repr__(self) -> str: ...

class ScatterData:
    def __init__(self, x: ArrayLike, y: ArrayLike) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    def __repr__(self) -> str: ...

class ScatterZData:
    def __init__(self, x: ArrayLike, y: ArrayLike, z: ArrayLike) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    @property
    def z(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @z.setter
    def z(self, arg: ArrayLike, /) -> None: ...

    def __repr__(self) -> str: ...

class BarData:
    def __init__(self, x: ArrayLike, height: ArrayLike) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def height(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @height.setter
    def height(self, arg: ArrayLike, /) -> None: ...

    def __repr__(self) -> str: ...

class HeatmapData:
    """
    data is (rows, cols), row-major as passed; values come back rounded
    to float32, which is how sextant stores them.
    """

    def __init__(self, data: ArrayLike, xrange: tuple[float, float], yrange: tuple[float, float]) -> None: ...

    @property
    def data(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @data.setter
    def data(self, arg: ArrayLike, /) -> None: ...

    @property
    def xrange(self) -> tuple[float, float]: ...

    @xrange.setter
    def xrange(self, arg: tuple[float, float], /) -> None: ...

    @property
    def yrange(self) -> tuple[float, float]: ...

    @yrange.setter
    def yrange(self, arg: tuple[float, float], /) -> None: ...

    def __repr__(self) -> str: ...

class Bar3DData:
    """
    heights and bottoms are (len(u), len(v)); bottoms is None when every bar
    stands on the bar3d() call's `bottom`.
    """

    def __init__(self, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike, bottoms: ArrayLike | None = None) -> None: ...

    @property
    def orient(self) -> sextant._enums.PlaneOrientation: ...

    @orient.setter
    def orient(self, arg: PlaneOrientationLike, /) -> None: ...

    @property
    def u(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @u.setter
    def u(self, arg: ArrayLike, /) -> None: ...

    @property
    def v(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @v.setter
    def v(self, arg: ArrayLike, /) -> None: ...

    @property
    def heights(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @heights.setter
    def heights(self, arg: ArrayLike, /) -> None: ...

    @property
    def bottoms(self) -> numpy.typing.NDArray[numpy.float64] | None: ...

    @bottoms.setter
    def bottoms(self, arg: ArrayLike | None, /) -> None: ...

    def __repr__(self) -> str: ...

class SurfaceData:
    """heights is (len(u), len(v))."""

    def __init__(self, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike) -> None: ...

    @property
    def orient(self) -> sextant._enums.PlaneOrientation: ...

    @orient.setter
    def orient(self, arg: PlaneOrientationLike, /) -> None: ...

    @property
    def u(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @u.setter
    def u(self, arg: ArrayLike, /) -> None: ...

    @property
    def v(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @v.setter
    def v(self, arg: ArrayLike, /) -> None: ...

    @property
    def heights(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @heights.setter
    def heights(self, arg: ArrayLike, /) -> None: ...

    def __repr__(self) -> str: ...

class SurfaceTriData:
    """
    tri is (n, 3) uint32: as passed, or the Delaunay triangulation made from
    an orientation. colors is None for a flat mesh.
    """

    def __init__(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, tri: ArrayLike, colors: ArrayLike | None = None) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    @property
    def z(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @z.setter
    def z(self, arg: ArrayLike, /) -> None: ...

    @property
    def tri(self) -> numpy.typing.NDArray[numpy.uint32]: ...

    @tri.setter
    def tri(self, arg: ArrayLike, /) -> None: ...

    @property
    def colors(self) -> numpy.typing.NDArray[numpy.float64] | None: ...

    @colors.setter
    def colors(self, arg: ArrayLike | None, /) -> None: ...

    def __repr__(self) -> str: ...

class Scatter3DData:
    """colors is None for a flat series."""

    def __init__(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, colors: ArrayLike | None = None) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    @property
    def z(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @z.setter
    def z(self, arg: ArrayLike, /) -> None: ...

    @property
    def colors(self) -> numpy.typing.NDArray[numpy.float64] | None: ...

    @colors.setter
    def colors(self, arg: ArrayLike | None, /) -> None: ...

    def __repr__(self) -> str: ...

class Line3DData:
    """colors is None for a flat path."""

    def __init__(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, colors: ArrayLike | None = None) -> None: ...

    @property
    def x(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @x.setter
    def x(self, arg: ArrayLike, /) -> None: ...

    @property
    def y(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @y.setter
    def y(self, arg: ArrayLike, /) -> None: ...

    @property
    def z(self) -> numpy.typing.NDArray[numpy.float64]: ...

    @z.setter
    def z(self, arg: ArrayLike, /) -> None: ...

    @property
    def colors(self) -> numpy.typing.NDArray[numpy.float64] | None: ...

    @colors.setter
    def colors(self, arg: ArrayLike | None, /) -> None: ...

    def __repr__(self) -> str: ...

class Axes:
    def line(self, x: ArrayLike, y: ArrayLike | None = None, *, err: ErrorBar | None = None, **opts: Unpack[LineOptions]) -> Axes:
        """
        line(x, y=None, *, err=None, **opts)

        A line through (x, y); line(y) plots y against 0, 1, 2, ...

        Keyword options (LineOptions): color, linewidth, linestyle, name, show_legend, alpha, loop, errorbar, hint_labels.
        """

    def scatter(self, x: ArrayLike, y: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[ScatterOptions]) -> Axes:
        """
        scatter(x, y, *, err=None, **opts)

        Markers at (x, y).

        Keyword options (ScatterOptions): color, size, marker, name, show_legend, alpha, edgecolor, edge_alpha, edge_linewidth, errorbar, hint_labels.
        """

    def scatter_z(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[ScatterZOptions]) -> Axes:
        """
        scatter_z(x, y, z, *, err=None, **opts)

        Markers at (x, y), coloured by z through cmap/vmin/vmax.

        Keyword options (ScatterZOptions): cmap, size, marker, alpha, edgecolor, edge_alpha, edge_linewidth, vmin, vmax, colorbar, name, show_legend, errorbar, hint_labels.
        """

    def bar(self, x: ArrayLike, height: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[BarOptions]) -> Axes:
        """
        bar(x, height, *, err=None, **opts)

        Bars centred on x.

        Keyword options (BarOptions): color, width, alpha, name, show_legend, edgecolor, linewidth, errorbar, hint_labels.
        """

    def heatmap(self, data: ArrayLike, xrange: tuple[float, float], yrange: tuple[float, float], **opts: Unpack[HeatmapOptions]) -> Axes:
        """
        heatmap(data, xrange, yrange, **opts)

        A 2-D array (rows, cols) drawn over xrange x yrange, (lo, hi) tuples of outer cell edges.

        Keyword options (HeatmapOptions): cmap, vmin, vmax, colorbar, name, origin, contours, contour_color, contour_linewidth, contour_labels, contour_fontsize, hint_labels.
        """

    def imshow(self, data: ArrayLike, **opts: Unpack[HeatmapOptions]) -> Axes:
        """
        imshow(data, **opts)

        heatmap() over x in [0, cols], y in [0, rows].

        Keyword options (HeatmapOptions): cmap, vmin, vmax, colorbar, name, origin, contours, contour_color, contour_linewidth, contour_labels, contour_fontsize, hint_labels.
        """

    def cla(self) -> Axes:
        """Clear all plot objects (on Axes, also reset limits)."""

    def line_count(self) -> int: ...

    def scatter_count(self) -> int: ...

    def scatter_z_count(self) -> int: ...

    def bar_count(self) -> int: ...

    def heatmap_count(self) -> int: ...

    def line_data(self, i: int) -> LineData: ...

    def scatter_data(self, i: int) -> ScatterData: ...

    def scatter_z_data(self, i: int) -> ScatterZData: ...

    def bar_data(self, i: int) -> BarData:
        """bar() and hist() alike."""

    def heatmap_data(self, i: int) -> HeatmapData:
        """heatmap() and imshow() alike."""

    @overload
    def set_line_data(self, i: int, data: LineData) -> Axes: ...

    @overload
    def set_line_data(self, i: int, x: ArrayLike, y: ArrayLike) -> Axes: ...

    @overload
    def set_scatter_data(self, i: int, data: ScatterData) -> Axes: ...

    @overload
    def set_scatter_data(self, i: int, x: ArrayLike, y: ArrayLike) -> Axes: ...

    @overload
    def set_scatter_z_data(self, i: int, data: ScatterZData) -> Axes: ...

    @overload
    def set_scatter_z_data(self, i: int, x: ArrayLike, y: ArrayLike, z: ArrayLike) -> Axes: ...

    @overload
    def set_bar_data(self, i: int, data: BarData) -> Axes: ...

    @overload
    def set_bar_data(self, i: int, x: ArrayLike, height: ArrayLike) -> Axes: ...

    @overload
    def set_heatmap_data(self, i: int, data: HeatmapData) -> Axes: ...

    @overload
    def set_heatmap_data(self, i: int, data: ArrayLike, xrange: tuple[float, float], yrange: tuple[float, float]) -> Axes: ...

    def hist(self, data: ArrayLike, bins: int = 10, *, density: bool = False, cumulative: bool = False, **opts: Unpack[BarOptions]) -> Axes:
        """
        hist(data, bins=10, *, density=False, cumulative=False, **opts)

        Histogram as bars. width defaults to 1.0 here (bins touch), not bar()'s 0.8.

        Keyword options (BarOptions): color, width, alpha, name, show_legend, edgecolor, linewidth, errorbar, hint_labels.
        """

    def set_title(self, text: str, fontsize: float = 18.0) -> Axes: ...

    def set_xtitle(self, text: str, fontsize: float = 16.5) -> Axes: ...

    def set_ytitle(self, text: str, fontsize: float = 16.5) -> Axes: ...

    def set_xlim(self, lo: float, hi: float) -> Axes: ...

    def set_ylim(self, lo: float, hi: float) -> Axes: ...

    def grid(self, enable: bool = True, **opts: Unpack[GridOptions]) -> Axes:
        """
        grid(enable=True, **opts)

        Grid lines.

        Keyword options (GridOptions): color, linestyle, linewidth.
        """

    def set_axes_style(self, **opts: Unpack[AxesStyle]) -> Axes:
        """
        set_axes_style(**opts)

        Spines, ticks, labels and titles. Unnamed fields reset to their defaults.

        Keyword options (AxesStyle): background, spine_color, spine_linewidth, spine_bottom, spine_left, spine_top, spine_right, xaxis_y, xaxis_z, yaxis_x, yaxis_z, zaxis_x, zaxis_y, origin_x, origin_y, origin_z, frame_margin, show_xticks, show_yticks, show_zticks, tick_color, tick_length, tick_linewidth, label_color, label_fontsize, title_color, title_fontsize, xtitle_color, xtitle_fontsize, ytitle_color, ytitle_fontsize, ztitle_color, ztitle_fontsize, font_path.
        """

    def legend(self, **opts: Unpack[LegendOptions]) -> Axes:
        """
        legend(**opts)

        Show the legend (series with a name).

        Keyword options (LegendOptions): anchor, margin, offset_x, offset_y, fontsize, frameon, text_color, frame_color, border_color, border_linewidth, font_path.
        """

    def set_colorbar_style(self, **opts: Unpack[ColorbarOptions]) -> Axes:
        """
        set_colorbar_style(**opts)

        Style shared by this axes' colorbars; a colorbar itself is asked for with colorbar=True on heatmap/scatter_z.

        Keyword options (ColorbarOptions): anchor, width, margin, offset_x, offset_y, fontsize, text_color, border_color, border_linewidth, font_path.
        """

    def set_xticks(self, positions: ArrayLike, labels: Sequence[str] = []) -> Axes: ...

    def set_yticks(self, positions: ArrayLike, labels: Sequence[str] = []) -> Axes: ...

    def title(self) -> str: ...

    def xtitle(self) -> str: ...

    def ytitle(self) -> str: ...

    def xlim(self) -> tuple[float, float]:
        """The x limits as drawn: set_xlim()'s, or the data's auto scale."""

    def ylim(self) -> tuple[float, float]: ...

class Plane2D:
    """
    A 2D plane in a 3D scene (Axes3D.plane()), carrying the 2D plot kinds in the
    parent's data coordinates along its two axes: xy -> (x, y), yz -> (y, z),
    zx -> (z, x). Limits, ticks and titles belong to the parent.
    """

    def line(self, x: ArrayLike, y: ArrayLike | None = None, *, err: ErrorBar | None = None, **opts: Unpack[LineOptions]) -> Plane2D:
        """
        line(x, y=None, *, err=None, **opts)

        A line through (x, y); line(y) plots y against 0, 1, 2, ...

        Keyword options (LineOptions): color, linewidth, linestyle, name, show_legend, alpha, loop, errorbar, hint_labels.
        """

    def scatter(self, x: ArrayLike, y: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[ScatterOptions]) -> Plane2D:
        """
        scatter(x, y, *, err=None, **opts)

        Markers at (x, y).

        Keyword options (ScatterOptions): color, size, marker, name, show_legend, alpha, edgecolor, edge_alpha, edge_linewidth, errorbar, hint_labels.
        """

    def scatter_z(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[ScatterZOptions]) -> Plane2D:
        """
        scatter_z(x, y, z, *, err=None, **opts)

        Markers at (x, y), coloured by z through cmap/vmin/vmax.

        Keyword options (ScatterZOptions): cmap, size, marker, alpha, edgecolor, edge_alpha, edge_linewidth, vmin, vmax, colorbar, name, show_legend, errorbar, hint_labels.
        """

    def bar(self, x: ArrayLike, height: ArrayLike, *, err: ErrorBar | None = None, **opts: Unpack[BarOptions]) -> Plane2D:
        """
        bar(x, height, *, err=None, **opts)

        Bars centred on x.

        Keyword options (BarOptions): color, width, alpha, name, show_legend, edgecolor, linewidth, errorbar, hint_labels.
        """

    def heatmap(self, data: ArrayLike, xrange: tuple[float, float], yrange: tuple[float, float], **opts: Unpack[HeatmapOptions]) -> Plane2D:
        """
        heatmap(data, xrange, yrange, **opts)

        A 2-D array (rows, cols) drawn over xrange x yrange, (lo, hi) tuples of outer cell edges.

        Keyword options (HeatmapOptions): cmap, vmin, vmax, colorbar, name, origin, contours, contour_color, contour_linewidth, contour_labels, contour_fontsize, hint_labels.
        """

    def imshow(self, data: ArrayLike, **opts: Unpack[HeatmapOptions]) -> Plane2D:
        """
        imshow(data, **opts)

        heatmap() over x in [0, cols], y in [0, rows].

        Keyword options (HeatmapOptions): cmap, vmin, vmax, colorbar, name, origin, contours, contour_color, contour_linewidth, contour_labels, contour_fontsize, hint_labels.
        """

    def cla(self) -> Plane2D:
        """Clear all plot objects (on Axes, also reset limits)."""

    def line_count(self) -> int: ...

    def scatter_count(self) -> int: ...

    def scatter_z_count(self) -> int: ...

    def bar_count(self) -> int: ...

    def heatmap_count(self) -> int: ...

    def line_data(self, i: int) -> LineData: ...

    def scatter_data(self, i: int) -> ScatterData: ...

    def scatter_z_data(self, i: int) -> ScatterZData: ...

    def bar_data(self, i: int) -> BarData:
        """bar() and hist() alike."""

    def heatmap_data(self, i: int) -> HeatmapData:
        """heatmap() and imshow() alike."""

    @overload
    def set_line_data(self, i: int, data: LineData) -> Plane2D: ...

    @overload
    def set_line_data(self, i: int, x: ArrayLike, y: ArrayLike) -> Plane2D: ...

    @overload
    def set_scatter_data(self, i: int, data: ScatterData) -> Plane2D: ...

    @overload
    def set_scatter_data(self, i: int, x: ArrayLike, y: ArrayLike) -> Plane2D: ...

    @overload
    def set_scatter_z_data(self, i: int, data: ScatterZData) -> Plane2D: ...

    @overload
    def set_scatter_z_data(self, i: int, x: ArrayLike, y: ArrayLike, z: ArrayLike) -> Plane2D: ...

    @overload
    def set_bar_data(self, i: int, data: BarData) -> Plane2D: ...

    @overload
    def set_bar_data(self, i: int, x: ArrayLike, height: ArrayLike) -> Plane2D: ...

    @overload
    def set_heatmap_data(self, i: int, data: HeatmapData) -> Plane2D: ...

    @overload
    def set_heatmap_data(self, i: int, data: ArrayLike, xrange: tuple[float, float], yrange: tuple[float, float]) -> Plane2D: ...

    def set_offset(self, offset: float) -> Plane2D:
        """Position along the plane's normal axis, in data units."""

    def set_alpha(self, alpha: float) -> Plane2D:
        """Whole-plane opacity; multiplies the objects' own alpha."""

    def orientation(self) -> sextant._enums.PlaneOrientation: ...

    def offset(self) -> float: ...

class Axes3D:
    def bar3d(self, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike, *, bottoms: ArrayLike | None = None, **opts: Unpack[Bar3DOptions]) -> Axes3D:
        """
        bar3d(orient, u, v, heights, *, bottoms=None, **opts)

        Bars on the grid u x v, standing along orient's normal ('xy' -> along z). heights (and bottoms)
        are (len(u), len(v)) or flat, u major.

        Keyword options (Bar3DOptions): color, alpha, width, depth, bottom, shading, edges, edgecolor, edge_alpha, edge_linewidth, name, show_legend, hint_labels.
        """

    def surface(self, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike, **opts: Unpack[SurfaceOptions]) -> Axes3D:
        """
        surface(orient, u, v, heights, **opts)

        A surface over the grid u x v (at least 2 x 2), rising along orient's normal; heights as bar3d.

        Keyword options (SurfaceOptions): color, colormap, cmap, vmin, vmax, colorbar, name, show_legend, alpha, shading, edges, edgecolor, edge_alpha, edge_linewidth, hint_labels.
        """

    def surface_tri(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, triangles: ArrayLike | None = None, *, orient: PlaneOrientationLike | None = None, colors: ArrayLike | None = None, **opts: Unpack[SurfaceTriOptions]) -> Axes3D:
        """
        surface_tri(x, y, z, triangles=None, *, orient=None, colors=None, **opts)

        A sheet on a triangulated mesh. Give exactly one of triangles ((n, 3) or flat, any integer dtype)
        and orient (Delaunay triangulation of the points projected onto that plane). colors, one per
        vertex, colormaps the mesh.

        Keyword options (SurfaceTriOptions): color, cmap, vmin, vmax, colorbar, name, show_legend, alpha, shading, edges, edgecolor, edge_alpha, edge_linewidth, hint_labels.
        """

    def scatter3d(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, *, colors: ArrayLike | None = None, err: ErrorBar3D | None = None, **opts: Unpack[Scatter3DOptions]) -> Axes3D:
        """
        scatter3d(x, y, z, *, colors=None, err=None, **opts)

        Markers at the points; colors (one per point) colormaps them. In 3D z is a coordinate.

        Keyword options (Scatter3DOptions): color, size, marker, alpha, edgecolor, edge_alpha, edge_linewidth, depthshade, cmap, vmin, vmax, colorbar, name, show_legend, errorbar, hint_labels.
        """

    def line3d(self, x: ArrayLike, y: ArrayLike, z: ArrayLike, *, colors: ArrayLike | None = None, err: ErrorBar3D | None = None, **opts: Unpack[Line3DOptions]) -> Axes3D:
        """
        line3d(x, y, z, *, colors=None, err=None, **opts)

        A path through the points in order.

        Keyword options (Line3DOptions): color, linewidth, alpha, loop, depthshade, cmap, vmin, vmax, colorbar, name, show_legend, errorbar, hint_labels.
        """

    def plane(self, orient: PlaneOrientationLike, offset: float = 0.0, **opts: Unpack[Plane2DOptions]) -> Plane2D:
        """
        plane(orient, offset=0.0, **opts)

        A Plane2D spanning orient's two axes at offset (data units) along the third.

        Keyword options (Plane2DOptions): alpha, visible.
        """

    def plane_count(self) -> int: ...

    def plane_at(self, i: int) -> Plane2D:
        """
        The i-th plane plane() made -- the same object; the index a Pick event's plane names.
        """

    def set_title(self, text: str, fontsize: float = 18.0) -> Axes3D: ...

    def set_xtitle(self, text: str, fontsize: float = 16.5) -> Axes3D: ...

    def set_ytitle(self, text: str, fontsize: float = 16.5) -> Axes3D: ...

    def set_ztitle(self, text: str, fontsize: float = 16.5) -> Axes3D: ...

    def set_xlim(self, lo: float, hi: float) -> Axes3D: ...

    def set_ylim(self, lo: float, hi: float) -> Axes3D: ...

    def set_zlim(self, lo: float, hi: float) -> Axes3D: ...

    def set_xticks(self, positions: ArrayLike, labels: Sequence[str] = []) -> Axes3D: ...

    def set_yticks(self, positions: ArrayLike, labels: Sequence[str] = []) -> Axes3D: ...

    def set_zticks(self, positions: ArrayLike, labels: Sequence[str] = []) -> Axes3D: ...

    def grid(self, enable: bool = True, **opts: Unpack[GridOptions]) -> Axes3D:
        """
        grid(enable=True, **opts)

        Grid lines on the three back panes (on by default).

        Keyword options (GridOptions): color, linestyle, linewidth.
        """

    def set_axes_style(self, **opts: Unpack[AxesStyle]) -> Axes3D:
        """
        set_axes_style(**opts)

        Axis annotation, shared with 2D. Unnamed fields reset to their defaults.

        Keyword options (AxesStyle): background, spine_color, spine_linewidth, spine_bottom, spine_left, spine_top, spine_right, xaxis_y, xaxis_z, yaxis_x, yaxis_z, zaxis_x, zaxis_y, origin_x, origin_y, origin_z, frame_margin, show_xticks, show_yticks, show_zticks, tick_color, tick_length, tick_linewidth, label_color, label_fontsize, title_color, title_fontsize, xtitle_color, xtitle_fontsize, ytitle_color, ytitle_fontsize, ztitle_color, ztitle_fontsize, font_path.
        """

    def set_box_style(self, **opts: Unpack[Box3DStyle]) -> Axes3D:
        """
        set_box_style(**opts)

        The box's panes and margin. Unnamed fields reset to their defaults.

        Keyword options (Box3DStyle): panes, pane_color, pane_edge_color, margin.
        """

    def set_box_aspect(self, aspect: tuple[float, float, float]) -> Axes3D:
        """Box side lengths as an (x, y, z) tuple; (1, 1, 1) is a cube."""

    def legend(self, **opts: Unpack[LegendOptions]) -> Axes3D:
        """
        legend(**opts)

        Keys every named series of this axes, then of its planes.

        Keyword options (LegendOptions): anchor, margin, offset_x, offset_y, fontsize, frameon, text_color, frame_color, border_color, border_linewidth, font_path.
        """

    def set_colorbar_style(self, **opts: Unpack[ColorbarOptions]) -> Axes3D:
        """
        set_colorbar_style(**opts)

        Style of every colorbar in the cell, planes' included.

        Keyword options (ColorbarOptions): anchor, width, margin, offset_x, offset_y, fontsize, text_color, border_color, border_linewidth, font_path.
        """

    def set_view(self, azimuth: float, elevation: float) -> Axes3D:
        """Degrees; elevation is clamped to +-89."""

    def set_camera(self, **opts: Unpack[Camera3D]) -> Axes3D:
        """
        set_camera(**opts)

        Replace the camera; unnamed fields take their defaults. ax.set_camera(**ax.camera()) round-trips.

        Keyword options (Camera3D): azimuth, elevation, target, zoom, projection, fov.
        """

    def camera(self) -> dict:
        """
        The camera as a dict: azimuth, elevation, target (x, y, z), zoom, projection, fov.
        """

    def set_projection(self, mode: ProjectionLike) -> Axes3D:
        """'orthographic' or 'perspective'."""

    def set_fov(self, degrees: float) -> Axes3D:
        """Perspective field of view, clamped to [5, 120]."""

    def set_default_camera(self, **opts: Unpack[Camera3D]) -> Axes3D:
        """
        set_default_camera(**opts)

        The camera a double-click in the window resets to.

        Keyword options (Camera3D): azimuth, elevation, target, zoom, projection, fov.
        """

    def cla(self) -> Axes3D: ...

    def title(self) -> str: ...

    def xtitle(self) -> str: ...

    def ytitle(self) -> str: ...

    def ztitle(self) -> str: ...

    def xlim(self) -> tuple[float, float]: ...

    def ylim(self) -> tuple[float, float]: ...

    def zlim(self) -> tuple[float, float]: ...

    def bar3d_count(self) -> int: ...

    def surface_count(self) -> int: ...

    def surface_tri_count(self) -> int: ...

    def scatter3d_count(self) -> int: ...

    def line3d_count(self) -> int: ...

    def bar3d_data(self, i: int) -> Bar3DData: ...

    def surface_data(self, i: int) -> SurfaceData: ...

    def surface_tri_data(self, i: int) -> SurfaceTriData: ...

    def scatter3d_data(self, i: int) -> Scatter3DData: ...

    def line3d_data(self, i: int) -> Line3DData: ...

    @overload
    def set_bar3d_data(self, i: int, data: Bar3DData) -> Axes3D: ...

    @overload
    def set_bar3d_data(self, i: int, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike, bottoms: ArrayLike | None = None) -> Axes3D: ...

    @overload
    def set_surface_data(self, i: int, data: SurfaceData) -> Axes3D: ...

    @overload
    def set_surface_data(self, i: int, orient: PlaneOrientationLike, u: ArrayLike, v: ArrayLike, heights: ArrayLike) -> Axes3D: ...

    @overload
    def set_surface_tri_data(self, i: int, data: SurfaceTriData) -> Axes3D: ...

    @overload
    def set_surface_tri_data(self, i: int, x: ArrayLike, y: ArrayLike, z: ArrayLike, triangles: ArrayLike, colors: ArrayLike | None = None) -> Axes3D: ...

    @overload
    def set_scatter3d_data(self, i: int, data: Scatter3DData) -> Axes3D: ...

    @overload
    def set_scatter3d_data(self, i: int, x: ArrayLike, y: ArrayLike, z: ArrayLike, colors: ArrayLike | None = None) -> Axes3D: ...

    @overload
    def set_line3d_data(self, i: int, data: Line3DData) -> Axes3D: ...

    @overload
    def set_line3d_data(self, i: int, x: ArrayLike, y: ArrayLike, z: ArrayLike, colors: ArrayLike | None = None) -> Axes3D: ...

class SvgSaveReport:
    """
    scene_order_exact False: part of a 3D scene was left in plain depth
    order (a budget ran out); `warning` says which and how to raise it.
    """

    @property
    def scene_order_exact(self) -> bool: ...

    @property
    def splits(self) -> int: ...

    @property
    def tests(self) -> int: ...

    @property
    def warning(self) -> str: ...

    def __repr__(self) -> str: ...

def set_repr_formats(*args) -> None:
    """
    set_repr_formats(*formats)

    What a Figure offers Jupyter/IPython to display it: 'png' (the default), 'svg', both,
    or none. SVG of a 3D scene can be slow to order, so it is opt-in.
    """

class FrameStats:
    @property
    def frames(self) -> int: ...

    @property
    def total_ms(self) -> float: ...

    @property
    def last_ms(self) -> float: ...

    @property
    def max_ms(self) -> float: ...

    def __repr__(self) -> str: ...

class Figure:
    def __init__(self, **opts: Unpack[FigureOptions]) -> None:
        """
        Figure(**opts)

        A figure. Nothing is shown until show(); savefig() works without a window.

        Keyword options (FigureOptions): width, height, title, resizable, dpi, subplot_col_gap, subplot_row_gap, margins, background, panel_width, supersample, vsync, theme.
        """

    def connect(self, kind: EventKindLike, callback: Callable) -> int:
        """
        Call callback(event) for events of `kind` (an EventKind, its name, or matplotlib's:
        'button_press_event', 'pick_event', ...). Returns an id for disconnect().
        Callbacks run on the thread that delivers events -- during show(), wait_closed(),
        run(), poll_events() or dispatch_events(), or at an interactive prompt -- so a
        script that never waits sees none. An exception is reported through
        sys.unraisablehook and delivery goes on; KeyboardInterrupt is raised by the wait.
        """

    def disconnect(self, id: int) -> None:
        """
        Stop a callback, including for events already queued. Unknown ids are ignored.
        """

    def dispatch_events(self) -> int:
        """Deliver this figure's queued events now; returns how many."""

    def axes(self) -> Axes:
        """The single axes of a 1x1 grid (made on first use)."""

    @overload
    def add_subplot(self, rows: int, cols: int, index: int) -> Axes:
        """
        The subplot at 1-based `index` of a rows x cols grid; `index` may be a (first, last) span.
        The first call fixes the grid; returns the existing subplot at that cell or span.
        """

    @overload
    def add_subplot(self, rows: int, cols: int, index: tuple[int, int]) -> Axes: ...

    @overload
    def add_subplot(self, index: int) -> Axes:
        """On the grid an earlier call fixed."""

    @overload
    def add_subplot(self, index: tuple[int, int]) -> Axes: ...

    @overload
    def add_subplot3d(self, rows: int, cols: int, index: int) -> Axes3D:
        """
        A 3D subplot on the same grid as add_subplot(), same rules; a cell holding a 2D axes throws.
        """

    @overload
    def add_subplot3d(self, rows: int, cols: int, index: tuple[int, int]) -> Axes3D: ...

    @overload
    def add_subplot3d(self, index: int) -> Axes3D: ...

    @overload
    def add_subplot3d(self, index: tuple[int, int]) -> Axes3D: ...

    def suptitle(self, text: str, fontsize: float = 21.0) -> None: ...

    def set_suptitle_style(self, **opts: Unpack[SuptitleOptions]) -> None:
        """
        set_suptitle_style(**opts)

        Unnamed fields reset to their defaults.

        Keyword options (SuptitleOptions): fontsize, color, font_path, align, offset_x, offset_y.
        """

    def set_margins(self, **opts: Unpack[FigureMargins]) -> None:
        """
        set_margins(**opts)

        Figure edge to subplot grid, in pixels. Unnamed sides reset to 10.

        Keyword options (FigureMargins): left, right, top, bottom.
        """

    def set_background(self, color: str | tuple[float, ...]) -> None:
        """
        The fill behind the whole figure (default light gray). Alpha 0 leaves a PNG or SVG transparent there.
        """

    def set_col_ratios(self, ratios: Sequence[float]) -> None:
        """Relative column widths, e.g. [2, 1]; [] = equal."""

    def set_row_ratios(self, ratios: Sequence[float]) -> None: ...

    def col_ratios(self) -> list[float]: ...

    def row_ratios(self) -> list[float]: ...

    def resize(self, width: int, height: int) -> None:
        """Resize the plot area (what savefig() writes)."""

    def size_for_frame(self, frame_w: int, frame_h: int, slot_index: int = 1) -> tuple[int, int]:
        """
        (width, height) at which subplot slot_index's data frame is frame_w x frame_h.
        """

    def resize_to_frame(self, frame_w: int, frame_h: int, slot_index: int = 1) -> None: ...

    def show(self, block: bool | None = None) -> None:
        """
        Open the window. block=None blocks until it closes, except in an
        interactive session (REPL, IPython, Jupyter), where the window keeps
        working between statements. A shown figure is kept, with its callbacks,
        until its window closes, even with no reference left to it.
        """

    def close(self) -> None: ...

    def is_open(self) -> bool: ...

    def wait_closed(self, timeout: float | None = None) -> bool:
        """
        Wait until the window has closed (True) or timeout seconds passed (False).
        """

    def refresh(self) -> None:
        """Publish changes to an open window."""

    def frame_stats(self) -> FrameStats: ...

    def savefig(self, fname: str | os.PathLike[str] | IO[Any], *, format: str | None = None, width: int = 0, height: int = 0, **opts: Unpack[ExportOptions]) -> SvgSaveReport | None:
        """
        savefig(fname, *, format=None, width=0, height=0, **opts)

        Write the figure to fname: a path (str or os.PathLike) or a file object with write().
        format is 'png' or 'svg'; by default the path's extension, and PNG for a file object.
        A text file object gets SVG as str, a binary one bytes. width/height <= 0 use the
        figure's size. Keyword options: PngExportOptions (peel_layers, dpi) or SvgExportOptions (max_splits, max_tests).
        Returns the SvgSaveReport for SVG, None for PNG.
        """

    def render_png(self, *, width: int = 0, height: int = 0, **opts: Unpack[PngExportOptions]) -> bytes:
        """
        render_png(*, width=0, height=0, **opts)

        The PNG file savefig() would write, as bytes.

        Keyword options (PngExportOptions): peel_layers, dpi.
        """

    def render_svg(self, *, width: int = 0, height: int = 0, **opts: Unpack[SvgExportOptions]) -> tuple[str, SvgSaveReport]:
        """
        render_svg(*, width=0, height=0, **opts)

        (svg_text, SvgSaveReport): the SVG savefig() would write, and whether its 3D order is exact.

        Keyword options (SvgExportOptions): max_splits, max_tests.
        """

    def render_rgba(self, *, width: int = 0, height: int = 0, **opts: Unpack[PngExportOptions]) -> numpy.typing.NDArray[numpy.uint8]:
        """
        render_rgba(*, width=0, height=0, **opts)

        The rendered figure as a (height, width, 4) uint8 array, top row first; width/height <= 0 use the figure's size.

        Keyword options (PngExportOptions): peel_layers, dpi.
        """

    def __enter__(self) -> Figure: ...

    def __exit__(self, *args) -> None: ...

class Event:
    """
    One event, as a callback connected with Figure.connect() receives it. Every kind
    has every field; the ones its kind does not fill keep their defaults (NaN for the
    data coordinates, -1 for indices). Pixel coordinates are the figure's: logical
    pixels from the top left of the plot area.
    """

    @property
    def kind(self) -> sextant._enums.EventKind: ...

    @property
    def mods(self) -> int:
        """Modifier bits: 1 ctrl, 2 shift, 4 alt, 8 super (see modifiers)."""

    @property
    def modifiers(self) -> tuple:
        """
        The held modifiers by name: ('ctrl', 'shift', 'alt', 'super') in that order.
        """

    @property
    def button(self) -> int:
        """mouse_down/mouse_up/pick: 0 left, 1 right, 2 middle."""

    @property
    def double_click(self) -> bool: ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def axes(self) -> int:
        """
        The subplot under (x, y), as the index add_subplot() takes (a span: its first
        cell), or -1. inaxes is the object itself.
        """

    @property
    def inaxes(self) -> Axes | Axes3D | None:
        """The Axes or Axes3D under (x, y), or None."""

    @property
    def has_data(self) -> bool:
        """
        Whether xdata/ydata(/zdata) are set: over a 2D axes, or where a 3D cursor ray
        meets a Plane2D.
        """

    @property
    def xdata(self) -> float: ...

    @property
    def ydata(self) -> float: ...

    @property
    def zdata(self) -> float: ...

    @property
    def scroll_x(self) -> float: ...

    @property
    def scroll_y(self) -> float:
        """Wheel notches, positive away from the user; queued ones are summed."""

    @property
    def consumed(self) -> sextant._enums.EventConsumed:
        """
        What sextant itself did with the input (informational; nothing is suppressed).
        """

    @property
    def key(self) -> str:
        """key_down/key_up: 'a', 'A', 'ctrl+a', 'escape', 'f5', 'left', ..."""

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def pick_kind(self) -> sextant._enums.PickKind: ...

    @property
    def pick_object(self) -> int:
        """
        Index within its kind: the i of line_data(i), bar3d_data(i), ... (on the plane
        when pick_plane >= 0).
        """

    @property
    def pick_index(self) -> int: ...

    @property
    def pick_row(self) -> int: ...

    @property
    def pick_col(self) -> int: ...

    @property
    def pick_plane(self) -> int:
        """Axes3D.plane_at() index of the plane the picked object is on, or -1."""

    def __repr__(self) -> str: ...

def set_message_handler(handler: Callable[[str], None] | None) -> Callable[[str], None] | None:
    """
    Route sextant's diagnostics to handler(message: str); None restores the default,
    warnings.warn(message, RuntimeWarning). Returns the previous handler.
    """

def poll_events() -> None:
    """
    Pump window events once and deliver every figure's queued events on this thread.
    On macOS this is the pump and must run on the main thread (RuntimeError elsewhere).
    """

def run() -> None:
    """Block until every open figure has closed, delivering their events."""
