"""Write src/sextant/_sextant.pyi, the type stub of the native module.

    uv run python tools/gen_stubs.py            # write it
    uv run python tools/gen_stubs.py --check    # exit 1 if it is out of date

nanobind.stubgen gives the classes and signatures. This adds what nanobind
cannot know, from the binding's own tables:

- each call's ``**opts`` as ``Unpack[<Struct>]``, a TypedDict of that option
  struct's fields (``_option_fields()``, the field tables of src/ext/options.h;
  the struct is the one the call's docstring names);
- ``<Enum>Like``, what an enum argument takes: the member, or one of the
  names and aliases the C++ caster matches verbatim (``_enum_tables()``).
  The caster also folds case and '_', '-', ' ', which a Literal cannot say.
"""

import json
import re
import sys
from pathlib import Path

from nanobind.stubgen import StubGen

import sextant._sextant as native

ROOT = Path(__file__).resolve().parents[1]
STUB = ROOT / "src" / "sextant" / "_sextant.pyi"

# A call whose options are one of several structs gets a TypedDict of them all.
MERGED = {("PngExportOptions", "SvgExportOptions"): "ExportOptions"}


def enum_aliases():
    out = []
    for cls, table in native._enum_tables().items():
        values = list(table["names"]) + [a for a in table["aliases"] if a not in table["names"]]
        literal = ", ".join(json.dumps(v) for v in values)
        out.append(f"{cls}Like: TypeAlias = sextant._enums.{cls} | Literal[{literal}]")
    return out


def typed_dicts():
    out = []
    for struct, fields in native._option_fields().items():
        out.append(f"class {struct}(TypedDict, total=False):")
        out += [f"    {name}: {ann}" for name, ann in fields.items()]
        out.append("")
    for parts, name in MERGED.items():
        out += [f"class {name}({', '.join(parts)}, total=False): ...", ""]
    return out


def options_struct(doc):
    """The TypedDict a docstring's "Keyword options" line names."""
    m = re.search(r"Keyword options \((\w+)\)", doc)
    if m:
        return m.group(1)
    m = re.search(r"Keyword options: (.*)", doc)
    if m:
        parts = tuple(re.findall(r"(\w+) \(", m.group(1)))
        if parts in MERGED:
            return MERGED[parts]
    return None


def type_kwargs(lines):
    """`**opts` -> `**opts: Unpack[<Struct>]`, the struct from the docstring below."""
    out = list(lines)
    for i, line in enumerate(out):
        if not line.lstrip().startswith("def ") or "**opts)" not in line:
            continue
        # The docstring runs until the next definition.
        doc = []
        for nxt in out[i + 1:]:
            if re.match(r"\s*(def |class |@)", nxt):
                break
            doc.append(nxt)
        struct = options_struct("\n".join(doc))
        if struct is None:
            sys.exit(f"gen_stubs: no 'Keyword options' struct in the docstring of:\n{line}")
        out[i] = line.replace("**opts)", f"**opts: Unpack[{struct}])")
    return out


def generate():
    sg = StubGen(native, include_docstrings=True, quiet=True)
    sg.put(native)
    lines = sg.get().splitlines()

    # The generated block goes before the first class or function.
    first = next(i for i, l in enumerate(lines) if re.match(r"(class |def |@)", l))
    imports = lines[:first]
    while imports and not imports[-1].strip():
        imports.pop()
    head = [
        "",
        "import collections.abc",
        "from typing import Literal, TypedDict",
        "",
        "from numpy.typing import ArrayLike",
        "from typing_extensions import TypeAlias, Unpack",
    ]
    if "import sextant._enums" not in imports:
        head += ["", "import sextant._enums"]
    head += ["", "", "# Generated by tools/gen_stubs.py from the binding's name and field tables.", ""]
    head += enum_aliases() + ["", ""] + typed_dicts() + [""]
    body = type_kwargs(lines[first:])
    return "\n".join(imports + head + body).rstrip("\n") + "\n"


def main():
    text = generate()
    if "--check" in sys.argv[1:]:
        current = STUB.read_text(encoding="utf-8").replace("\r\n", "\n") if STUB.exists() else ""
        if current != text:
            sys.exit(f"{STUB.relative_to(ROOT)} is out of date: run tools/gen_stubs.py")
        return
    STUB.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {STUB.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
